version: 2

project_name: hwp2md

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: hwp2md
    main: ./cmd/hwp2md
    binary: hwp2md
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features"
      regexp: '^.*?Add|Implement|Create|feat(\(.+\))?!?:.*$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?Fix|Resolve|Correct|fix(\(.+\))?!?:.*$'
      order: 1
    - title: "Improvements"
      regexp: '^.*?Update|Change|Refactor|Improve|perf(\(.+\))?!?:.*$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\(.+\))?!?:.*$'
      order: 3
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: roboco-io
    name: hwp2md
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## hwp2md {{ .Version }}

    HWP(한글 워드프로세서) 문서를 Markdown으로 변환하는 CLI 도구입니다.

    ### 설치

    #### 바이너리 다운로드
    아래에서 플랫폼에 맞는 바이너리를 다운로드하세요.

    #### Go 설치
    ```bash
    go install github.com/roboco-io/hwp2md/cmd/hwp2md@{{ .Version }}
    ```

    ### 주요 기능
    - HWPX 문서를 Markdown으로 변환
    - LLM 기반 포맷팅 (Claude, GPT, Gemini, Ollama 지원)
    - 테이블, 이미지, 목록 지원

  footer: |

    ---

    **Full Changelog**: https://github.com/roboco-io/hwp2md/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew (향후 지원 예정)
# brews:
#   - repository:
#       owner: roboco-io
#       name: homebrew-tap
#     homepage: https://github.com/roboco-io/hwp2md
#     description: HWP to Markdown converter CLI tool
#     license: MIT
